### ISSUE TITLE
Можно ли адаптировать схему под ESP8266?

### ISSUE THREAD

**Issue by zenkdev** [AlexGyver/AC_Dimmer#1]
ДД. Можно ли адаптировать схему под ESP8266?

**Comment by Wanderernk** [comment]
@trailblazer2006 Привет.
Ценность ESP8266 - WiFi. Но при включенном вайфае и отработки прерываний точность регулирования будет не очень.
Можете попробовать. Нужно взять слаботочный MOC, пересчитать R2, возможно R5.
Если будете использовать другой TRIAC, то R1. 
Кстати, на схеме нет снаббера.

@AlexGyver Привет!
Я бы поправил описание в части оптосимистора - MOC3020 не подойдет из-за высокого тока открытия. Сам сначала не проверил, купил детали по списку. Сейчас сел собирать и понял, что от порта ардуины тока будет хватать впритык, что рискованно.
Также стоит добавить упоминание, что R2 всегда пересчитывать под выбранный MOC302x

**Comment by IgorFX** [comment]
Alex если усложнить задачу управление 3,3 в. Zero cross обрабатывает рассыпуха, не контролер. Нагрузка лампы и вентиляторы до 200Вт. Компактная схема у тебя получилась,можно расширить функционал - универсальность!

**Comment by ckretus** [comment]
Было бы здорово чтобы появился выпуск под esp8266, либо под другие библиотеки таймера, которые поддерживаются большим количеством плат под ардуино.

**Comment by AlexGyver** [comment]
Для универсальности есть скетч с delay, без таймера
